import { Wrench, Truck, Package, Beaker, Warehouse } from 'lucide-react'

export const products = [
  {
    id: '1',
    name: 'Organic Rice',
    category: 'Grains',
    price: 450,
    currency: 'USD/ton',
    supplier: 'Happy Farms India',
    image: 'https://images.unsplash.com/photo-1586985289688-ca3bab4d4e66?w=400&h=300&fit=crop',
    origin: 'India',
    quantity: 5000,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: '2',
    name: 'Premium Wheat',
    category: 'Grains',
    price: 380,
    currency: 'USD/ton',
    supplier: 'Golden Harvest',
    image: 'https://images.unsplash.com/photo-1537521403529-c0beaf3d3601?w=400&h=300&fit=crop',
    origin: 'Ukraine',
    quantity: 8000,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: '3',
    name: 'Fresh Tomatoes',
    category: 'Vegetables',
    price: 650,
    currency: 'USD/ton',
    supplier: 'Fresh Valley',
    image: 'https://images.unsplash.com/photo-1592921870789-04563e271b1b?w=400&h=300&fit=crop',
    origin: 'Turkey',
    quantity: 2000,
    rating: 4.9,
    reviews: 203,
  },
  {
    id: '4',
    name: 'Cocoa Beans',
    category: 'Cash Crops',
    price: 2800,
    currency: 'USD/ton',
    supplier: 'Ivory Coast Exports',
    image: 'https://images.unsplash.com/photo-1599599810694-b308ca884cb9?w=400&h=300&fit=crop',
    origin: 'Ivory Coast',
    quantity: 1500,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: '5',
    name: 'Corn (Maize)',
    category: 'Grains',
    price: 420,
    currency: 'USD/ton',
    supplier: 'Midwest Grains',
    image: 'https://images.unsplash.com/photo-1585074294335-493dba05bd13?w=400&h=300&fit=crop',
    origin: 'USA',
    quantity: 12000,
    rating: 4.5,
    reviews: 112,
  },
  {
    id: '6',
    name: 'Coffee Beans',
    category: 'Cash Crops',
    price: 3200,
    currency: 'USD/ton',
    supplier: 'Colombian Roasts',
    image: 'https://images.unsplash.com/photo-1447933601403-0c6688bcf566?w=400&h=300&fit=crop',
    origin: 'Colombia',
    quantity: 2000,
    rating: 4.8,
    reviews: 178,
  },
  {
    id: '7',
    name: 'Sweet Potatoes',
    category: 'Vegetables',
    price: 720,
    currency: 'USD/ton',
    supplier: 'Harvest Hills',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
    origin: 'Vietnam',
    quantity: 3000,
    rating: 4.6,
    reviews: 95,
  },
  {
    id: '8',
    name: 'Soybeans',
    category: 'Grains',
    price: 550,
    currency: 'USD/ton',
    supplier: 'Global AgriTrade',
    image: 'https://images.unsplash.com/photo-1560960999-a8d5cf09eb29?w=400&h=300&fit=crop',
    origin: 'Brazil',
    quantity: 10000,
    rating: 4.7,
    reviews: 134,
  },
]

export const rentalServices = [
  {
    id: '1',
    name: 'Tractor Rental',
    category: 'Equipment Rental',
    description: 'Modern tractors for plowing, tilling, and field preparation available for daily or seasonal hire.',
    icon: Wrench,
  },
  {
    id: '2',
    name: 'Harvester Machine',
    category: 'Equipment Rental',
    description: 'Industrial harvesting equipment to maximize yield and minimize crop loss during harvest season.',
    icon: Wrench,
  },
  {
    id: '3',
    name: 'Agricultural Transport',
    category: 'Transportation',
    description: 'Reliable logistics solutions for transporting agricultural products from farm to market.',
    icon: Truck,
  },
  {
    id: '4',
    name: 'Cold Chain Storage',
    category: 'Storage',
    description: 'Climate-controlled warehousing to preserve product freshness and extend shelf life.',
    icon: Package,
  },
  {
    id: '5',
    name: 'Soil Testing & Analysis',
    category: 'Processing',
    description: 'Professional soil analysis and testing services to optimize your farming practices.',
    icon: Beaker,
  },
  {
    id: '6',
    name: 'Grain Processing Facility',
    category: 'Processing',
    description: 'State-of-the-art grain milling and processing services for your agricultural products.',
    icon: Warehouse,
  },
  {
    id: '7',
    name: 'Export Consulting',
    category: 'Consulting',
    description: 'Expert guidance on international trade regulations, documentation, and logistics.',
    icon: Truck,
  },
  {
    id: '8',
    name: 'Crop Insurance Advisory',
    category: 'Consulting',
    description: 'Professional advice on protecting your crops with comprehensive insurance coverage.',
    icon: Beaker,
  },
]

export const marketData = [
  {
    id: '1',
    commodity: 'Wheat',
    region: 'North America',
    price: 280,
    change24h: 2.5,
    volume: 5000,
    trend: 'up' as const,
  },
  {
    id: '2',
    commodity: 'Corn',
    region: 'North America',
    price: 210,
    change24h: -1.2,
    volume: 8000,
    trend: 'down' as const,
  },
  {
    id: '3',
    commodity: 'Soybeans',
    region: 'South America',
    price: 340,
    change24h: 3.8,
    volume: 4500,
    trend: 'up' as const,
  },
  {
    id: '4',
    commodity: 'Rice',
    region: 'Asia',
    price: 420,
    change24h: 1.5,
    volume: 6000,
    trend: 'up' as const,
  },
  {
    id: '5',
    commodity: 'Wheat',
    region: 'Europe',
    price: 300,
    change24h: 0.8,
    volume: 3500,
    trend: 'up' as const,
  },
]

export const priceHistory = [
  { date: 'Jan 1', price: 280 },
  { date: 'Jan 8', price: 285 },
  { date: 'Jan 15', price: 282 },
  { date: 'Jan 22', price: 290 },
  { date: 'Jan 29', price: 295 },
  { date: 'Feb 5', price: 288 },
  { date: 'Feb 12', price: 292 },
  { date: 'Feb 19', price: 298 },
  { date: 'Feb 26', price: 305 },
  { date: 'Mar 5', price: 312 },
]

export const categories = [
  { id: 'grains', name: 'Grains', icon: '🌾', count: 1250 },
  { id: 'vegetables', name: 'Vegetables', icon: '🥬', count: 890 },
  { id: 'fruits', name: 'Fruits', icon: '🍎', count: 654 },
  { id: 'spices', name: 'Spices', icon: '🌶️', count: 432 },
  { id: 'cashcrops', name: 'Cash Crops', icon: '☕', count: 298 },
  { id: 'seeds', name: 'Seeds', icon: '🌱', count: 567 },
]

export const insights = [
  {
    id: '1',
    title: 'Global Wheat Shortage Drives Prices Up',
    description: 'Recent weather patterns in major wheat producing regions are expected to reduce yields by 15-20% this season.',
    category: 'Market Analysis',
    trend: 'up' as const,
    percentage: 18,
  },
  {
    id: '2',
    title: 'Organic Produce Demand Surges in Europe',
    description: 'European retailers report 35% increase in organic vegetable orders, driven by growing consumer health consciousness.',
    category: 'Trends',
    trend: 'up' as const,
    percentage: 35,
  },
  {
    id: '3',
    title: 'Asian Market Expansion',
    description: 'Asian buyers are actively seeking new suppliers for diverse agricultural products.',
    category: 'Trade News',
    trend: 'up' as const,
    percentage: 22,
  },
  {
    id: '4',
    title: 'Sustainable Farming Certifications in Demand',
    description: 'Buyers increasingly require sustainability certifications, creating new standards across the supply chain.',
    category: 'Sustainability',
    trend: 'up' as const,
    percentage: 12,
  },
]
